export const carsJson = [{
  'UID_PHYSICAL': '167726',
  'UID_VEHICULO': 33,
  'UID_EXTERNAL': '1018',
  'ESTATUS_VEHICULO': 'Vehiculo en teleoperacion',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'CDMX',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '54:43:06',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '150300',
  'UID_VEHICULO': 34,
  'UID_EXTERNAL': '1019',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 19.346652,
  'UBICACION_GPS_LON': -99.169732,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '132522',
  'UID_VEHICULO': 36,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 19.368972,
  'UBICACION_GPS_LON': -99.177567,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '129411',
  'UID_VEHICULO': 37,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo en viaje de usuario',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 19.346668,
  'UBICACION_GPS_LON': -99.169685,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '130302',
  'UID_VEHICULO': 39,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '244624',
  'UID_VEHICULO': 40,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo en teleoperacion',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '03:17:28',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '246975',
  'UID_VEHICULO': 41,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '252403',
  'UID_VEHICULO': 42,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 58,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '246546',
  'UID_VEHICULO': 43,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 36,
  'UBICACION_GPS_LAT': 19.347293,
  'UBICACION_GPS_LON': -99.170082,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '2017f14',
  'VERSION_FIRMWARE': '23c5',
}, {
  'UID_PHYSICAL': '258970',
  'UID_VEHICULO': 44,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '258855',
  'UID_VEHICULO': 45,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '255984',
  'UID_VEHICULO': 46,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957642,
  'UBICACION_GPS_LON': -84.225342,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '271478',
  'UID_VEHICULO': 47,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '213553',
  'UID_VEHICULO': 48,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '272690',
  'UID_VEHICULO': 49,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957695,
  'UBICACION_GPS_LON': -84.225158,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '266148',
  'UID_VEHICULO': 50,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.95758,
  'UBICACION_GPS_LON': -84.224762,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '285759',
  'UID_VEHICULO': 51,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '239517',
  'UID_VEHICULO': 52,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '256107',
  'UID_VEHICULO': 53,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957795,
  'UBICACION_GPS_LON': -84.225197,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '222653',
  'UID_VEHICULO': 54,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 95,
  'UBICACION_GPS_LAT': 33.957722,
  'UBICACION_GPS_LON': -84.225037,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '254649',
  'UID_VEHICULO': 55,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '213579',
  'UID_VEHICULO': 56,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.9577,
  'UBICACION_GPS_LON': -84.2251,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '278200',
  'UID_VEHICULO': 57,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957848,
  'UBICACION_GPS_LON': -84.225442,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '213876',
  'UID_VEHICULO': 58,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '258848',
  'UID_VEHICULO': 59,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '260158',
  'UID_VEHICULO': 60,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '223800',
  'UID_VEHICULO': 61,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957642,
  'UBICACION_GPS_LON': -84.224792,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '287805',
  'UID_VEHICULO': 62,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '260018',
  'UID_VEHICULO': 63,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '239509',
  'UID_VEHICULO': 64,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 37.3862,
  'UBICACION_GPS_LON': -122.078513,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '702:47:22',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '258913',
  'UID_VEHICULO': 65,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '269597',
  'UID_VEHICULO': 66,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '258905',
  'UID_VEHICULO': 67,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '213918',
  'UID_VEHICULO': 68,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '21edfc9',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '260141',
  'UID_VEHICULO': 69,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '277400',
  'UID_VEHICULO': 70,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '254664',
  'UID_VEHICULO': 71,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.95766,
  'UBICACION_GPS_LON': -84.22509,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '262899',
  'UID_VEHICULO': 72,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.95824,
  'UBICACION_GPS_LON': -84.225723,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '218644',
  'UID_VEHICULO': 73,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957668,
  'UBICACION_GPS_LON': -84.224877,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '260182',
  'UID_VEHICULO': 74,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '251306',
  'UID_VEHICULO': 75,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957607,
  'UBICACION_GPS_LON': -84.225297,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '251074',
  'UID_VEHICULO': 76,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 76,
  'UBICACION_GPS_LAT': 19.346762,
  'UBICACION_GPS_LON': -99.169968,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '8fcb',
}, {
  'UID_PHYSICAL': '235572',
  'UID_VEHICULO': 77,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.957787,
  'UBICACION_GPS_LON': -84.225205,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '263897',
  'UID_VEHICULO': 78,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '771337',
  'UID_VEHICULO': 79,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 37.3853,
  'UBICACION_GPS_LON': -122.076,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '725:48:22',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '267435',
  'UID_VEHICULO': 80,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '767319',
  'UID_VEHICULO': 81,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 33.95758,
  'UBICACION_GPS_LON': -84.224937,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '574351',
  'UID_VEHICULO': 82,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo en viaje de usuario',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '754002',
  'UID_VEHICULO': 83,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 33.957618,
  'UBICACION_GPS_LON': -84.225747,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '754572',
  'UID_VEHICULO': 84,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.957665,
  'UBICACION_GPS_LON': -84.225517,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '773838',
  'UID_VEHICULO': 85,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '755280',
  'UID_VEHICULO': 86,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 37.384552,
  'UBICACION_GPS_LON': -122.076408,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '726:24:21',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '775999',
  'UID_VEHICULO': 87,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '775361',
  'UID_VEHICULO': 88,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 92,
  'UBICACION_GPS_LAT': 37.390338,
  'UBICACION_GPS_LON': -122.076813,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '771907',
  'UID_VEHICULO': 89,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.957737,
  'UBICACION_GPS_LON': -84.225128,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '765222',
  'UID_VEHICULO': 90,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '777730',
  'UID_VEHICULO': 91,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '218545',
  'UID_VEHICULO': 92,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 33.957917,
  'UBICACION_GPS_LON': -84.225045,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': '770818',
  'UID_VEHICULO': 93,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.95773,
  'UBICACION_GPS_LON': -84.225472,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '768911',
  'UID_VEHICULO': 94,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 37.385162,
  'UBICACION_GPS_LON': -122.076255,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '218:59:56',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '782102',
  'UID_VEHICULO': 95,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.957733,
  'UBICACION_GPS_LON': -84.22535,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '780353',
  'UID_VEHICULO': 96,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 37.3853,
  'UBICACION_GPS_LON': -122.076,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '243:48:51',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '57749fc',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '754911',
  'UID_VEHICULO': 97,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 33.957302,
  'UBICACION_GPS_LON': -84.224167,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '773192',
  'UID_VEHICULO': 98,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '773929',
  'UID_VEHICULO': 99,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 11,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '771063',
  'UID_VEHICULO': 100,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 33.957713,
  'UBICACION_GPS_LON': -84.225105,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '293902',
  'UID_VEHICULO': 101,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '777920',
  'UID_VEHICULO': 102,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 33.95728,
  'UBICACION_GPS_LON': -84.224883,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '254888',
  'UID_VEHICULO': 103,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '278242',
  'UID_VEHICULO': 104,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 99,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '263640',
  'UID_VEHICULO': 106,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '273995',
  'UID_VEHICULO': 107,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '254854',
  'UID_VEHICULO': 108,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '259002',
  'UID_VEHICULO': 109,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '21edfc9',
  'VERSION_FIRMWARE': '',
}, {
  'UID_PHYSICAL': 'unknow',
  'UID_VEHICULO': 110,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': 'No disponible',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': null,
  'VERSION_FIRMWARE': null,
}, {
  'UID_PHYSICAL': '269142',
  'UID_VEHICULO': 111,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 19.388296666666665,
  'UBICACION_GPS_LON': -99.08635666666666,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '05:21:51',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '263814',
  'UID_VEHICULO': 112,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 33,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '263798',
  'UID_VEHICULO': 113,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 98,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '838:59:59',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'b4b5b8b',
  'VERSION_FIRMWARE': 'e814',
}, {
  'UID_PHYSICAL': '254482',
  'UID_VEHICULO': 114,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 19.346773,
  'UBICACION_GPS_LON': -99.169945,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '358:02:25',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'e8dd3dc',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '259945',
  'UID_VEHICULO': 115,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '09:14:41',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '268375',
  'UID_VEHICULO': 116,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 95,
  'UBICACION_GPS_LAT': 19.346767,
  'UBICACION_GPS_LON': -99.170005,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '578:29:01',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '9219ce0',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '214163',
  'UID_VEHICULO': 117,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 19.3467,
  'UBICACION_GPS_LON': -99.17,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '580:26:25',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '2017f14',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '251116',
  'UID_VEHICULO': 118,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 19.3467,
  'UBICACION_GPS_LON': -99.17,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '578:28:24',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '8c83b6b',
  'VERSION_FIRMWARE': '91a9',
}, {
  'UID_PHYSICAL': '',
  'UID_VEHICULO': 119,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '04:20:29',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '/NETE>',
  'UID_VEHICULO': 120,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': 'No disponible',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': null,
  'VERSION_FIRMWARE': null,
}, {
  'UID_PHYSICAL': '',
  'UID_VEHICULO': 121,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '196:11:02',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': 'XTRA=0',
  'UID_VEHICULO': 122,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 0,
  'UBICACION_GPS_LAT': 0,
  'UBICACION_GPS_LON': 0,
  'CIUDAD': 'No definida',
  'NOMBRE_OPERADOR': 'GoX',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '196:10:18',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': 'NA',
  'VERSION_FIRMWARE': 'NA',
}, {
  'UID_PHYSICAL': '123363',
  'UID_VEHICULO': 123,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 100,
  'UBICACION_GPS_LAT': 19.138997967870647,
  'UBICACION_GPS_LON': -98.06572280027655,
  'CIUDAD': 'CDMX',
  'NOMBRE_OPERADOR': 'Clevr',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '167:24:42',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '-',
  'VERSION_FIRMWARE': '-',
}, {
  'UID_PHYSICAL': '123364',
  'UID_VEHICULO': 124,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 75,
  'UBICACION_GPS_LAT': 19.235702065032086,
  'UBICACION_GPS_LON': -98.86757044335842,
  'CIUDAD': 'CDMX',
  'NOMBRE_OPERADOR': 'Clevr',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '167:24:14',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '-',
  'VERSION_FIRMWARE': '-',
}, {
  'UID_PHYSICAL': '123365',
  'UID_VEHICULO': 125,
  'UID_EXTERNAL': 'No disponible',
  'ESTATUS_VEHICULO': 'Vehiculo disponible',
  'NIVEL_BATERIA': 23,
  'UBICACION_GPS_LAT': 19.066356982557366,
  'UBICACION_GPS_LON': -98.34856932725259,
  'CIUDAD': 'CDMX',
  'NOMBRE_OPERADOR': 'Clevr',
  'FABRICANTE': 'No definido',
  'MODELO': 'No definido',
  'LAST_CONNECTION_UPDATE': '167:25:18',
  'ESTATUS_CONEXION': 13,
  'VERSION_BRAIN': '-',
  'VERSION_FIRMWARE': '-',
}]
